{
    "assignee": null,
    "body": "Hi,\r\nI am using WhatsAPI to sync contacts.\r\nHere is part of my code:\r\n--------------------------------------------------------------------------------------\r\nfunction onSyncResult($result)\r\n{\r\n    foreach($result->existing as $number)\r\n    {\r\n        echo \"$number exists<br />\";\r\n    }\r\n    foreach($result->nonExisting as $number)\r\n    {\r\n        echo \"$number does not exist<br />\";\r\n    }\r\n    die();//to break out of the while(true) loop\r\n}\r\n$wa = new WhatsProt($username, \"\", \"WhatsApp\", false);\r\n//bind event handler\r\n$wa->eventManager()->bind('onGetSyncResult', 'onSyncResult');\r\n$wa->connect();\r\necho '1';\r\n$wa->loginWithPassword($password);\r\necho '2';\r\n//send dataset to server\r\n$wa->sendSync($numbers);\r\n//wait for response\r\nwhile(true)\r\n{\r\n    $wa->pollMessage();\r\n}\r\n-----------------------------------------------------------------------------------------\r\nThis code run very well from my localhost, evenif I tried it 3 to 4 times.\r\n\r\nNow the problem is \r\nwhen I tried to run this code on my testing server it does not work.\r\nIn first attempt either it does not call 'onSyncResult' after login or gives 500 internal server error.\r\nAnd in just second attempt it blocks the number, means does not login.\r\n\r\nPlease give some solution or hint to solve this problem...\r\nThanks.",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1030/comments",
    "created_at": "2014-11-14T06:17:24Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1030/events",
    "html_url": "https://github.com/venomous0x/WhatsAPI/issues/1030",
    "id": 48738315,
    "labels": [],
    "labels_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1030/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1030,
    "state": "open",
    "title": "contact sync gives 500 internal server error",
    "updated_at": "2014-11-14T06:17:24Z",
    "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/1030",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/9737896?v=3",
        "events_url": "https://api.github.com/users/bhavesh50/events{/privacy}",
        "followers_url": "https://api.github.com/users/bhavesh50/followers",
        "following_url": "https://api.github.com/users/bhavesh50/following{/other_user}",
        "gists_url": "https://api.github.com/users/bhavesh50/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/bhavesh50",
        "id": 9737896,
        "login": "bhavesh50",
        "organizations_url": "https://api.github.com/users/bhavesh50/orgs",
        "received_events_url": "https://api.github.com/users/bhavesh50/received_events",
        "repos_url": "https://api.github.com/users/bhavesh50/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/bhavesh50/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bhavesh50/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/bhavesh50"
    }
}