{
    "assignee": null,
    "body": "[] Listen mode:\r\nPHP Warning:  socket_read(): unable to read from socket [0]: An established connection was aborted by the software in your host machine. in C:\\wamp\\www\\whatsapp\\whatsprot.class.php on line 140\r\n\r\nLine 140: $ret = socket_read( $this->_socket, 1024 );\r\n\r\nI think they changed the way of the connection and they drop script connection",
    "closed_at": "2012-11-07T22:46:05Z",
    "comment_data": [
        {
            "body": "I also tried to ping s.whatsapp.net ... but it was unreachable via ping and nslookup",
            "created_at": "2012-11-04T17:38:11Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10053006",
            "id": 10053006,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T17:38:11Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10053006",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2030376?v=3",
                "events_url": "https://api.github.com/users/eslamo/events{/privacy}",
                "followers_url": "https://api.github.com/users/eslamo/followers",
                "following_url": "https://api.github.com/users/eslamo/following{/other_user}",
                "gists_url": "https://api.github.com/users/eslamo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/eslamo",
                "id": 2030376,
                "login": "eslamo",
                "organizations_url": "https://api.github.com/users/eslamo/orgs",
                "received_events_url": "https://api.github.com/users/eslamo/received_events",
                "repos_url": "https://api.github.com/users/eslamo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/eslamo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/eslamo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/eslamo"
            }
        },
        {
            "body": "strange i dont receive this error. check if you can resolve dns from your machine that you launch the script",
            "created_at": "2012-11-04T18:45:45Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10053733",
            "id": 10053733,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T18:45:45Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10053733",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2720879?v=3",
                "events_url": "https://api.github.com/users/tribbolo/events{/privacy}",
                "followers_url": "https://api.github.com/users/tribbolo/followers",
                "following_url": "https://api.github.com/users/tribbolo/following{/other_user}",
                "gists_url": "https://api.github.com/users/tribbolo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tribbolo",
                "id": 2720879,
                "login": "tribbolo",
                "organizations_url": "https://api.github.com/users/tribbolo/orgs",
                "received_events_url": "https://api.github.com/users/tribbolo/received_events",
                "repos_url": "https://api.github.com/users/tribbolo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tribbolo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tribbolo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tribbolo"
            }
        },
        {
            "body": "Is kind of your problem, nslookup resolution is working. From an http protocol it's impossible to understand if the request comes from a script. So even if the problem would exist it's not related to the script. ",
            "created_at": "2012-11-04T18:47:40Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10053754",
            "id": 10053754,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T18:48:08Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10053754",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2271366?v=3",
                "events_url": "https://api.github.com/users/kerby82/events{/privacy}",
                "followers_url": "https://api.github.com/users/kerby82/followers",
                "following_url": "https://api.github.com/users/kerby82/following{/other_user}",
                "gists_url": "https://api.github.com/users/kerby82/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kerby82",
                "id": 2271366,
                "login": "kerby82",
                "organizations_url": "https://api.github.com/users/kerby82/orgs",
                "received_events_url": "https://api.github.com/users/kerby82/received_events",
                "repos_url": "https://api.github.com/users/kerby82/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kerby82/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kerby82/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kerby82"
            }
        },
        {
            "body": "i tried to connect from different servers using many real ips .. and i also have this issue ... is the script working with you fine [ login / sending ] ??\r\n\r\nI can ping / trace / nslookup & telnet bin-short.whatsapp.net 5222\r\n\r\nIt connects successfully .. but after debugging the script using echo socket_strerror(socket_last_error());\r\n\r\ni found this error No connection could be made because the target machine actively refused it.\r\n\r\n",
            "created_at": "2012-11-04T18:58:44Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10053886",
            "id": 10053886,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T20:02:41Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10053886",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2030376?v=3",
                "events_url": "https://api.github.com/users/eslamo/events{/privacy}",
                "followers_url": "https://api.github.com/users/eslamo/followers",
                "following_url": "https://api.github.com/users/eslamo/following{/other_user}",
                "gists_url": "https://api.github.com/users/eslamo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/eslamo",
                "id": 2030376,
                "login": "eslamo",
                "organizations_url": "https://api.github.com/users/eslamo/orgs",
                "received_events_url": "https://api.github.com/users/eslamo/received_events",
                "repos_url": "https://api.github.com/users/eslamo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/eslamo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/eslamo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/eslamo"
            }
        },
        {
            "body": "yes do the same from 50 minutes for me too, i think the new login autentication its required and the server drop the connection if the login fail",
            "created_at": "2012-11-04T20:08:57Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10054786",
            "id": 10054786,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T20:08:57Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10054786",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2720879?v=3",
                "events_url": "https://api.github.com/users/tribbolo/events{/privacy}",
                "followers_url": "https://api.github.com/users/tribbolo/followers",
                "following_url": "https://api.github.com/users/tribbolo/following{/other_user}",
                "gists_url": "https://api.github.com/users/tribbolo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tribbolo",
                "id": 2720879,
                "login": "tribbolo",
                "organizations_url": "https://api.github.com/users/tribbolo/orgs",
                "received_events_url": "https://api.github.com/users/tribbolo/received_events",
                "repos_url": "https://api.github.com/users/tribbolo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tribbolo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tribbolo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tribbolo"
            }
        },
        {
            "body": "in this moment the server timeout ... can't connect at all .. i think it's a maintenance case in wup servers. \r\n\r\nA connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond",
            "created_at": "2012-11-04T20:14:07Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10054843",
            "id": 10054843,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T20:14:35Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10054843",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2030376?v=3",
                "events_url": "https://api.github.com/users/eslamo/events{/privacy}",
                "followers_url": "https://api.github.com/users/eslamo/followers",
                "following_url": "https://api.github.com/users/eslamo/following{/other_user}",
                "gists_url": "https://api.github.com/users/eslamo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/eslamo",
                "id": 2030376,
                "login": "eslamo",
                "organizations_url": "https://api.github.com/users/eslamo/orgs",
                "received_events_url": "https://api.github.com/users/eslamo/received_events",
                "repos_url": "https://api.github.com/users/eslamo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/eslamo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/eslamo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/eslamo"
            }
        },
        {
            "body": "They have overload on their servers\r\n\r\nנשלח מה-iPhone שלי\r\n\r\nב-4 בנוב 2012, בשעה 22:14, eslamo <notifications@github.com> כתב/ה:\r\n\r\n> in this moment the server timeout ... can't connect at all .. i think it's a maintenance case in wup servers.\r\n> \r\n> —\r\n> Reply to this email directly or view it on GitHub.\r\n> ",
            "created_at": "2012-11-04T20:15:24Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10054858",
            "id": 10054858,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T20:15:24Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10054858",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1543770?v=3",
                "events_url": "https://api.github.com/users/davidste/events{/privacy}",
                "followers_url": "https://api.github.com/users/davidste/followers",
                "following_url": "https://api.github.com/users/davidste/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidste/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/davidste",
                "id": 1543770,
                "login": "davidste",
                "organizations_url": "https://api.github.com/users/davidste/orgs",
                "received_events_url": "https://api.github.com/users/davidste/received_events",
                "repos_url": "https://api.github.com/users/davidste/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/davidste/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidste/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/davidste"
            }
        },
        {
            "body": "yes i think so because whatsapp can't connect from mobile too\r\n\r\nthey changed their system status to say that they have a problem right now",
            "created_at": "2012-11-04T20:18:13Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10054883",
            "id": 10054883,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T20:19:44Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10054883",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2030376?v=3",
                "events_url": "https://api.github.com/users/eslamo/events{/privacy}",
                "followers_url": "https://api.github.com/users/eslamo/followers",
                "following_url": "https://api.github.com/users/eslamo/following{/other_user}",
                "gists_url": "https://api.github.com/users/eslamo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/eslamo",
                "id": 2030376,
                "login": "eslamo",
                "organizations_url": "https://api.github.com/users/eslamo/orgs",
                "received_events_url": "https://api.github.com/users/eslamo/received_events",
                "repos_url": "https://api.github.com/users/eslamo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/eslamo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/eslamo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/eslamo"
            }
        },
        {
            "body": "Service back t work again but it's unable to login .... is this general case or for me only ??",
            "created_at": "2012-11-04T20:37:52Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10055076",
            "id": 10055076,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T20:37:52Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10055076",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2030376?v=3",
                "events_url": "https://api.github.com/users/eslamo/events{/privacy}",
                "followers_url": "https://api.github.com/users/eslamo/followers",
                "following_url": "https://api.github.com/users/eslamo/following{/other_user}",
                "gists_url": "https://api.github.com/users/eslamo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/eslamo",
                "id": 2030376,
                "login": "eslamo",
                "organizations_url": "https://api.github.com/users/eslamo/orgs",
                "received_events_url": "https://api.github.com/users/eslamo/received_events",
                "repos_url": "https://api.github.com/users/eslamo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/eslamo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/eslamo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/eslamo"
            }
        },
        {
            "body": "yes its right changed autentication  we wait for new summit",
            "created_at": "2012-11-04T21:28:57Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10055677",
            "id": 10055677,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-04T21:28:57Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10055677",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2720879?v=3",
                "events_url": "https://api.github.com/users/tribbolo/events{/privacy}",
                "followers_url": "https://api.github.com/users/tribbolo/followers",
                "following_url": "https://api.github.com/users/tribbolo/following{/other_user}",
                "gists_url": "https://api.github.com/users/tribbolo/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tribbolo",
                "id": 2720879,
                "login": "tribbolo",
                "organizations_url": "https://api.github.com/users/tribbolo/orgs",
                "received_events_url": "https://api.github.com/users/tribbolo/received_events",
                "repos_url": "https://api.github.com/users/tribbolo/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tribbolo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tribbolo/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tribbolo"
            }
        },
        {
            "body": "whatsapp change chat protocol from 1.1 to 1.2\r\n\r\nprotocol 1.2 is harder than protocol 1.1\r\n",
            "created_at": "2012-11-05T09:40:45Z",
            "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135#issuecomment-10064761",
            "id": 10064761,
            "issue_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
            "updated_at": "2012-11-05T09:40:45Z",
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/comments/10064761",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2725572?v=3",
                "events_url": "https://api.github.com/users/alaamac/events{/privacy}",
                "followers_url": "https://api.github.com/users/alaamac/followers",
                "following_url": "https://api.github.com/users/alaamac/following{/other_user}",
                "gists_url": "https://api.github.com/users/alaamac/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/alaamac",
                "id": 2725572,
                "login": "alaamac",
                "organizations_url": "https://api.github.com/users/alaamac/orgs",
                "received_events_url": "https://api.github.com/users/alaamac/received_events",
                "repos_url": "https://api.github.com/users/alaamac/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/alaamac/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/alaamac/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/alaamac"
            }
        }
    ],
    "comments": 11,
    "comments_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135/comments",
    "created_at": "2012-11-04T17:34:28Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2384212?v=3",
                "events_url": "https://api.github.com/users/veno/events{/privacy}",
                "followers_url": "https://api.github.com/users/veno/followers",
                "following_url": "https://api.github.com/users/veno/following{/other_user}",
                "gists_url": "https://api.github.com/users/veno/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/veno",
                "id": 2384212,
                "login": "veno",
                "organizations_url": "https://api.github.com/users/veno/orgs",
                "received_events_url": "https://api.github.com/users/veno/received_events",
                "repos_url": "https://api.github.com/users/veno/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/veno/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/veno/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/veno"
            },
            "commit_id": "98ecb3a78fbcef4a1ccc7fab4a557ed9d1aaadae",
            "created_at": "2012-11-07T22:45:26Z",
            "event": "referenced",
            "id": 28814122,
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/events/28814122"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2384212?v=3",
                "events_url": "https://api.github.com/users/veno/events{/privacy}",
                "followers_url": "https://api.github.com/users/veno/followers",
                "following_url": "https://api.github.com/users/veno/following{/other_user}",
                "gists_url": "https://api.github.com/users/veno/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/veno",
                "id": 2384212,
                "login": "veno",
                "organizations_url": "https://api.github.com/users/veno/orgs",
                "received_events_url": "https://api.github.com/users/veno/received_events",
                "repos_url": "https://api.github.com/users/veno/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/veno/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/veno/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/veno"
            },
            "commit_id": null,
            "created_at": "2012-11-07T22:46:05Z",
            "event": "closed",
            "id": 28814258,
            "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/events/28814258"
        }
    ],
    "events_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135/events",
    "html_url": "https://github.com/venomous0x/WhatsAPI/issues/135",
    "id": 8090251,
    "labels": [],
    "labels_url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 135,
    "state": "closed",
    "title": "Whatsapp server closing connection to the script",
    "updated_at": "2012-11-07T22:46:05Z",
    "url": "https://api.github.com/repos/venomous0x/WhatsAPI/issues/135",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/2030376?v=3",
        "events_url": "https://api.github.com/users/eslamo/events{/privacy}",
        "followers_url": "https://api.github.com/users/eslamo/followers",
        "following_url": "https://api.github.com/users/eslamo/following{/other_user}",
        "gists_url": "https://api.github.com/users/eslamo/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/eslamo",
        "id": 2030376,
        "login": "eslamo",
        "organizations_url": "https://api.github.com/users/eslamo/orgs",
        "received_events_url": "https://api.github.com/users/eslamo/received_events",
        "repos_url": "https://api.github.com/users/eslamo/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/eslamo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eslamo/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/eslamo"
    }
}